name: sim

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: false
          extra-conf: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-substituters = https://nix-cache.fossi-foundation.org
            extra-trusted-public-keys = nix-cache.fossi-foundation.org:3+K59iFwXqKsL7BNu6Guy0v+uTlwsxYQxjspXzqLYQs=

      - name: Build Nix devShell
        run: |
          nix build \
            --no-link \
            --accept-flake-config \
            .#devShells.x86_64-linux.default

      - name: Clone PDK
        run: |
          nix develop --accept-flake-config --command make clone-pdk

      - run: nix develop --accept-flake-config --command make sim DUT=input_fifo
      - run: nix develop --accept-flake-config --command make sim DUT=evt2_decoder
      - run: nix develop --accept-flake-config --command make sim DUT=voxel_gesture_classifier
      - run: nix develop --accept-flake-config --command make sim DUT=voxel_mac_engine
      - run: nix develop --accept-flake-config --command make sim DUT=voxel_binning

      # - run: nix develop --accept-flake-config --command make sim DUT=voxel_bin_core # takes too long for GA

      - run: nix develop --accept-flake-config --command make clean
